FROM node:16-bullseye

RUN apt-get update 
RUN apt-get install -y \
  build-essential \
  pkg-config \
  python3
RUN npm config set python python3
RUN npm install --global code-server --unsafe-perm

WORKDIR /project

CMD code-server