FROM python:3.12.0a7-bullseye

RUN apt-get update 
RUN apt-get install -y \
  build-essential \
  pkg-config \
  python3

RUN curl -sL https://deb.nodesource.com/setup_16.x | bash -
RUN apt-get install -y nodejs
RUN npm config set python python3
RUN npm install --global minimist vscode-textmate @microsoft/1ds-core-js yauzl yazl spdlog vscode-regexpp vscode-proxy-agent @vscode/ripgrep xterm-headless keytar @parcel/watcher
RUN npm install --global code-server --unsafe-perm

WORKDIR /project

CMD code-server