services:
  db:
    image: dgraph/standalone:master
    #ports:
    #  - 8080:8080
  code: 
    image: nodecode
    ports: 
      - 8080
      - 5173
    #volumes:
    #   - "$HOME/.config:/root/.config"
    command:
      - /bin/sh
      - -c
      - |
        git clone https://github.com/yellowmachine/ika-example-dgraph.git .
        code-server --host 0.0.0.0 /project